spring:
  application:
    name: Secret providers
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none